"""Export service — real PDF/DOCX generation for parliamentary drafts."""

import io

from docx import Document as DocxDocument
from reportlab.pdfgen import canvas as pdf_canvas
from reportlab.lib.pagesizes import A4

from app.schemas.draft import DraftOut


def export_draft_pdf_bytes(draft: DraftOut) -> bytes:
    """Render a draft to a PDF (reportlab)."""
    buf = io.BytesIO()
    page = pdf_canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    page.setTitle(draft.title)

    margin = 54
    y = height - margin
    page.setFont("Helvetica-Bold", 16)
    page.drawString(margin, y, "DRAFT PARLIAMENTARY RESPONSE")
    y -= 20
    page.setFont("Helvetica", 9)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    page.drawString(
        margin,
        y,
        "Generated by CIL Search Studio - Executive Wing (confidential, pre-circulation)",
    )
    y -= 28
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, y, width - margin, y)
    y -= 18

    page.setFillColorRGB(0.067, 0.067, 0.067)
    page.setFont("Helvetica-Bold", 11)
    page.drawString(margin, y, f"Title: {draft.title}")
    y -= 22

    def draw_label(label: str) -> None:
        nonlocal y
        page.setFont("Helvetica-Bold", 10)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        page.drawString(margin, y, label)
        y -= 16

    def draw_wrapped(text: str, size: int = 10) -> None:
        nonlocal y
        page.setFont("Helvetica", size)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        words = text.split()
        line = ""
        for word in words:
            test = f"{line} {word}".strip()
            if page.stringWidth(test, "Helvetica", size) > width - 2 * margin:
                page.drawString(margin, y, line)
                y -= 14
                line = word
            else:
                line = test
        if line:
            page.drawString(margin, y, line)
            y -= 14
        y -= 6

    draw_label("Question")
    draw_wrapped(draft.preamble or "")
    y -= 8
    draw_label("Reply")
    draw_wrapped(draft.body)
    y -= 10

    # Sources footer
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, max(60, y), width - margin, max(60, y))
    page.setFont("Helvetica-Oblique", 8)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    sources = ", ".join(
        f"{c.documentName} (p.{c.pageNumber})" for c in draft.citations
    )
    page.drawString(margin, max(44, y - 14), f"Sources: {sources or '—'}")

    page.showPage()
    page.save()
    return buf.getvalue()


def export_draft_docx_bytes(draft: DraftOut) -> bytes:
    """Render a draft to a .docx (python-docx)."""
    doc = DocxDocument()
    doc.add_heading("DRAFT PARLIAMENTARY RESPONSE", level=1)
    p = doc.add_paragraph()
    run = p.add_run(
        "Generated by CIL Search Studio - Executive Wing "
        "(confidential, pre-circulation)"
    )
    run.italic = True
    run.font.size = 90000  # 9pt

    doc.add_paragraph()
    doc.add_heading(f"Title: {draft.title}", level=2)
    doc.add_heading("Question", level=3)
    doc.add_paragraph(draft.preamble or "")
    doc.add_heading("Reply", level=3)
    doc.add_paragraph(draft.body)

    sources = doc.add_paragraph()
    run = sources.add_run(
        "Sources: "
        + ", ".join(
            f"{c.documentName} (p.{c.pageNumber})" for c in draft.citations
        )
        or "—"
    )
    run.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
