"""Export service — real PDF/DOCX generation for parliamentary drafts."""

import io

from docx import Document as DocxDocument
from docx.shared import Pt
from reportlab.pdfgen import canvas as pdf_canvas
from reportlab.lib.pagesizes import A4

from app.schemas.draft import DraftOut

# Bottom margin: content never renders below this line — long drafts roll
# onto a continuation page instead of running off the sheet (previously the
# body simply overflows past the page edge and the overflow was lost).
BOTTOM_MARGIN = 64


def export_draft_pdf_bytes(draft: DraftOut) -> bytes:
    """Render a draft to a PDF (reportlab), paginating when it overflows."""
    buf = io.BytesIO()
    page = pdf_canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    page.setTitle(draft.title)

    margin = 54
    y = height - margin
    page.setTitle(draft.title)

    def new_page() -> None:
        nonlocal y
        page.showPage()
        y = height - margin
        page.setFont("Helvetica-Oblique", 8)
        page.setFillColorRGB(0.4, 0.4, 0.4)
        page.drawString(margin, y, f"{draft.title} (continued)")
        y -= 24
        page.setFillColorRGB(0.067, 0.067, 0.067)

    def ensure_space(needed: float) -> None:
        if y - needed < BOTTOM_MARGIN:
            new_page()

    page.setFont("Helvetica-Bold", 16)
    page.drawString(margin, y, "DRAFT PARLIAMENTARY RESPONSE")
    y -= 20
    page.setFont("Helvetica", 9)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    page.drawString(
        margin,
        y,
        "Generated by CIL Report Studio - Executive Wing (confidential, pre-circulation)",
    )
    y -= 28
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, y, width - margin, y)
    y -= 18

    page.setFillColorRGB(0.067, 0.067, 0.067)
    page.setFont("Helvetica-Bold", 11)
    page.drawString(margin, y, f"Title: {draft.title}")
    y -= 22

    def draw_label(label: str) -> None:
        nonlocal y
        ensure_space(16)
        page.setFont("Helvetica-Bold", 10)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        page.drawString(margin, y, label)
        y -= 16

    def draw_wrapped(text: str, size: int = 10) -> None:
        nonlocal y
        page.setFont("Helvetica", size)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        words = text.split()
        line = ""
        for word in words:
            test = f"{line} {word}".strip()
            if page.stringWidth(test, "Helvetica", size) > width - 2 * margin:
                ensure_space(14)
                page.setFont("Helvetica", size)
                page.setFillColorRGB(0.067, 0.067, 0.067)
                page.drawString(margin, y, line)
                y -= 14
                line = word
            else:
                line = test
        if line:
            ensure_space(14)
            page.setFont("Helvetica", size)
            page.setFillColorRGB(0.067, 0.067, 0.067)
            page.drawString(margin, y, line)
            y -= 14
        y -= 6

    draw_label("Question")
    draw_wrapped(draft.preamble or "")
    y -= 8
    draw_label("Reply")
    draw_wrapped(draft.body)
    y -= 10

    # Sources footer (kept on the current page only if it fully fits,
    # otherwise rolled onto a fresh continuation page).
    ensure_space(48)
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, y, width - margin, y)
    page.setFont("Helvetica-Oblique", 8)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    sources = ", ".join(
        f"{c.documentName} (p.{c.pageNumber})" for c in draft.citations
    )
    page.drawString(margin, y - 14, f"Sources: {sources or '—'}")

    page.showPage()
    page.save()
    return buf.getvalue()


def export_draft_docx_bytes(draft: DraftOut) -> bytes:
    """Render a draft to a .docx (python-docx)."""
    doc = DocxDocument()
    doc.add_heading("DRAFT PARLIAMENTARY RESPONSE", level=1)
    p = doc.add_paragraph()
    run = p.add_run(
        "Generated by CIL Report Studio - Executive Wing "
        "(confidential, pre-circulation)"
    )
    run.italic = True
    run.font.size = Pt(9)  # was 90000 EMU (~7.1pt) — actually 9pt now

    doc.add_paragraph()
    doc.add_heading(f"Title: {draft.title}", level=2)
    doc.add_heading("Question", level=3)
    doc.add_paragraph(draft.preamble or "")
    doc.add_heading("Reply", level=3)
    doc.add_paragraph(draft.body)

    sources = doc.add_paragraph()
    run = sources.add_run(
        "Sources: "
        + ", ".join(
            f"{c.documentName} (p.{c.pageNumber})" for c in draft.citations
        )
        or "—"
    )
    run.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
# ---------------------------------------------------------------------------
# Report Generation Studio exports (stateless: renders the posted report)
# ---------------------------------------------------------------------------
def export_report_pdf_bytes(report: "ReportOut") -> bytes:
    """Render a generated report to a PDF (reportlab), paginating on overflow."""
    buf = io.BytesIO()
    page = pdf_canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    margin = 54
    y = height - margin
    page.setTitle(report.title)

    def new_page() -> None:
        nonlocal y
        page.showPage()
        y = height - margin
        page.setFont("Helvetica-Oblique", 8)
        page.setFillColorRGB(0.4, 0.4, 0.4)
        page.drawString(margin, y, f"{report.title} (continued)")
        y -= 24
        page.setFillColorRGB(0.067, 0.067, 0.067)

    def ensure_space(needed: float) -> None:
        if y - needed < BOTTOM_MARGIN:
            new_page()

    def draw_wrapped(text: str, size: int = 10, indent: int = 0) -> None:
        nonlocal y
        page.setFont("Helvetica", size)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        max_width = width - 2 * margin - indent
        line = ""
        for word in text.split():
            test = f"{line} {word}".strip()
            if page.stringWidth(test, "Helvetica", size) > max_width:
                ensure_space(14)
                page.setFont("Helvetica", size)
                page.setFillColorRGB(0.067, 0.067, 0.067)
                page.drawString(margin + indent, y, line)
                y -= 14
                line = word
            else:
                line = test
        if line:
            ensure_space(14)
            page.setFont("Helvetica", size)
            page.setFillColorRGB(0.067, 0.067, 0.067)
            page.drawString(margin + indent, y, line)
            y -= 14

    page.setFont("Helvetica-Bold", 16)
    page.setFillColorRGB(0.067, 0.067, 0.067)
    page.drawString(margin, y, report.title[:80])
    y -= 20
    page.setFont("Helvetica", 9)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    page.drawString(
        margin,
        y,
        "CIL Report Studio (compiled from the committed corpus)",
    )
    y -= 14
    page.drawString(
        margin,
        y,
        f"Generated {report.generated_at:%d %b %Y %H:%M} UTC · "
        f"{report.source_count} cited sources · compiled in {report.compile_seconds:.1f}s",
    )
    y -= 14
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, y, width - margin, y)
    y -= 18
    page.setFillColorRGB(0.067, 0.067, 0.067)

    draw_wrapped(report.preamble, 10)
    y -= 8

    for section in report.sections:
        ensure_space(46)
        page.setFont("Helvetica-Bold", 12)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        page.drawString(margin, y, section.heading[:90])
        y -= 18
        for raw_line in section.body.splitlines():
            line = raw_line.strip()
            if not line:
                y -= 5
                continue
            if line.startswith(("-", "•")):
                ensure_space(14)
                page.setFont("Helvetica", 10)
                page.drawString(margin + 2, y, "•")
                draw_wrapped(line.lstrip("-• ").strip(), 10, indent=14)
            else:
                draw_wrapped(line, 10)
        y -= 8

    if report.key_figures:
        ensure_space(40)
        page.setFont("Helvetica-Bold", 12)
        page.setFillColorRGB(0.067, 0.067, 0.067)
        page.drawString(margin, y, "Key Figures")
        y -= 18
        for fig in report.key_figures:
            ensure_space(15)
            page.setFont("Helvetica-Bold", 10)
            page.setFillColorRGB(0.067, 0.067, 0.067)
            label = f"{fig.label}:"
            page.drawString(margin + 8, y, label[:60])
            label_width = page.stringWidth(label[:60], "Helvetica-Bold", 10)
            page.setFont("Helvetica", 10)
            page.drawString(margin + 14 + label_width, y, fig.value[:60])
            y -= 15
        y -= 8

    ensure_space(50)
    page.setStrokeColorRGB(0.85, 0.85, 0.85)
    page.line(margin, y, width - margin, y)
    y -= 16
    page.setFont("Helvetica-Bold", 9)
    page.setFillColorRGB(0.4, 0.4, 0.4)
    page.drawString(margin, y, "Sources")
    y -= 14
    for i, citation in enumerate(report.citations, start=1):
        ensure_space(13)
        page.setFont("Helvetica", 8)
        page.setFillColorRGB(0.4, 0.4, 0.4)
        page.drawString(
            margin, y, f"[{i}] {citation.documentName} — p.{citation.pageNumber}"
        )
        y -= 12

    page.showPage()
    page.save()
    return buf.getvalue()


def export_report_docx_bytes(report: "ReportOut") -> bytes:
    """Render a generated report to a .docx (python-docx)."""
    doc = DocxDocument()
    doc.add_heading(report.title, level=1)

    subtitle = doc.add_paragraph()
    run = subtitle.add_run(
        "CIL Report Studio "
        "(compiled from the committed corpus)"
    )
    run.italic = True
    run.font.size = Pt(9)

    meta = doc.add_paragraph()
    run = meta.add_run(
        f"Generated {report.generated_at:%d %b %Y %H:%M} UTC · "
        f"{report.source_count} cited sources · compiled in {report.compile_seconds:.1f}s"
    )
    run.font.size = Pt(9)

    doc.add_paragraph(report.preamble)

    for section in report.sections:
        doc.add_heading(section.heading, level=2)
        for raw_line in section.body.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(("-", "•")):
                doc.add_paragraph(line.lstrip("-• ").strip(), style="List Bullet")
            else:
                doc.add_paragraph(line)

    if report.key_figures:
        doc.add_heading("Key Figures", level=2)
        for fig in report.key_figures:
            doc.add_paragraph(f"{fig.label}: {fig.value}", style="List Bullet")

    if report.citations:
        doc.add_heading("Sources", level=2)
        for i, citation in enumerate(report.citations, start=1):
            doc.add_paragraph(
                f"[{i}] {citation.documentName} — p.{citation.pageNumber}"
            )

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
