/**
 * Export stubs for the Parliamentary Response Draft Generator.
 * - PDF:  generates a real, minimal standalone PDF client-side.
 * - DOCX: simulated pipeline — downloads a plain-text placeholder until the
 *   backend OOXML service is wired.
 */
import type { DraftDocument } from "@/lib/types";

function escapePdf(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLines(text: string, width = 92): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length > width) {
      lines.push(current.trim());
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  if (current) lines.push(current.trim());
  return lines;
}

/** Build a minimal, valid single-page PDF content stream for the draft. */
function buildPdfContent(draft: DraftDocument): string {
  const parts: string[] = ["BT"];
  const pushLine = (text: string, size: number, y: number) => {
    parts.push(`/F1 ${size} Tf 62 ${y.toFixed(0)} Td (${escapePdf(text)}) Tj`);
  };

  pushLine("DRAFT PARLIAMENTARY RESPONSE", 18, 740);
  pushLine(
    "Generated by CIL Search Studio - Executive Wing (confidential, pre-circulation)",
    9,
    715,
  );
  parts.push("0.85 0.85 0.85 rg 62 688 488 1 re f");
  pushLine(`Title: ${draft.title}`, 11, 662);

  let y = 636;
  pushLine("Question", 10, y);
  y -= 16;
  for (const line of wrapLines(draft.preamble, 88)) {
    pushLine(line, 10, y);
    y -= 14;
  }

  y -= 10;
  pushLine("Reply", 10, y);
  y -= 16;
  for (const line of wrapLines(draft.body, 88)) {
    pushLine(line, 10, y);
    y -= 14;
  }

  y -= 18;
  parts.push(`0.85 0.85 0.85 rg 62 ${Math.max(40, y - 16)} 488 1 re f`);
  pushLine(
    `Sources: ${draft.citations.map((c) => c.documentName).join(", ")}`,
    8,
    Math.max(26, y - 28),
  );
  parts.push("ET");
  return parts.join("\n");
}

/** Generate a standalone PDF string for a draft document. */
export function buildDraftPdf(draft: DraftDocument): string {
  const content = buildPdfContent(draft);
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  objects.forEach((obj, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 0; i < objects.length; i++) {
    pdf += `${String(offsets[i + 1]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return pdf;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadDraftAsPdf(draft: DraftDocument) {
  const pdf = buildDraftPdf(draft);
  const blob = new Blob([pdf], { type: "application/pdf" });
  triggerDownload(blob, "parliamentary-response-draft.pdf");
}

export function downloadDraftAsDocxStub(draft: DraftDocument) {
  const text = [
    "DRAFT PARLIAMENTARY RESPONSE (DOCX EXPORT STUB)",
    "=================================================",
    `Title: ${draft.title}`,
    "",
    "Question",
    draft.preamble,
    "",
    "Reply",
    draft.body,
    "",
    `Sources: ${draft.citations.map((c) => `${c.documentName} (p.${c.pageNumber})`).join(", ")}`,
  ].join("\n");
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  triggerDownload(blob, "parliamentary-response-draft.docx");
}
